services:

  dash:
    build: ./dash
    image: spongebob_dash:latest
    container_name: dash
    networks:
      - spongebob-net
    environment:
      - GOOGLE_REDIRECT_URI=http://localhost:3600
    ports:
      - 3600:3600
    depends_on:
      - scdown
  
  scdown:
    build: ./scdown
    image: spongebob_scdown:latest
    container_name: scdown
    networks:
      - spongebob-net
    volumes:
      - ./scdownloads:/app/scdownloads
    ports:
      - 7071:7071
      
networks:
  spongebob-net:
    driver: bridge

