services:
  main:
    build: ./main
    image: spongebob_main:latest
    container_name: main
    networks:
      - spongebob-net
    depends_on:
      - rabbitmq

  uploader:
    build: ./uploader
    image: spongebob_uploader:latest
    container_name: uploader
    networks:
      - spongebob-net
    depends_on:
      - rabbitmq
      - main
  
  rabbitmq:
    image: rabbitmq:4.1.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spongebob-net

networks:
  spongebob-net:
    driver: bridge
